# Generated by Django 5.2.8 on 2025-11-08 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('theme', models.JSONField(default=dict, help_text='Colors, fonts, styling configuration')),
                ('fields', models.JSONField(default=list, help_text='List of field configurations')),
                ('layout_style', models.CharField(choices=[('classic', 'Classic'), ('minimal', 'Minimal'), ('modern', 'Modern')], default='classic', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('active', models.BooleanField(default=True)),
                ('event_type', models.CharField(default='default', help_text='15-min, 30-min, 60-min, etc.', max_length=100)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
