# Generated by Django 5.2.8 on 2025-11-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
